---
- name: install mongodb
  hosts: all
  become: true
  tasks:

  - name: Add APT key
    apt_key:
      id: EA312927
      keyserver: keyserver.ubuntu.com

  - name: add mongodb repo to repo list
    ansible.builtin.apt_repository:
      repo: deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse
      state: present

  - name: install mongodb
    apt:
      name: mongodb-org
      state: present
      allow_unauthenticated: yes

  - name: enable mongodb
    ansible.builtin.service:
      name: mongod
      enabled: yes
      state: started
